insert into cliente (cli_name, cli_place, cli_bdate, cli_gender, cli_email) values ('Kaio Schoeneman', 'Aldeia de Paio Pires', str_to_date('2003.01.26','%Y.%m.%d'), 'M', 'kaioscho@gmail.com');
insert into cliente (cli_name, cli_place, cli_bdate, cli_gender, cli_email) values ('Leonardo Alves', 'Chelas', str_to_date('2004.07.15','%Y.%m.%d'), 'M','leoalves@gmail.com');
insert into cliente (cli_name, cli_place, cli_bdate, cli_gender, cli_email) values ('Vitoria Almeida', 'Pontinha', str_to_date('2005.11.25','%Y.%m.%d'), 'F', 'almeidavih@gmail.com');
insert into cliente (cli_name, cli_place, cli_bdate, cli_gender, cli_email) values ('Luis Felipe', 'Benfica', str_to_date('2002.06.13','%Y.%m.%d'), 'M', 'felipe@gmail.com');
insert into cliente (cli_name, cli_place, cli_bdate, cli_gender, cli_email) values ('Eduarda Thompson', 'Setúbal', str_to_date('2004.01.26','%Y.%m.%d'), 'F', 'thompsonduda@mac.com');
insert into cliente (cli_name, cli_place, cli_bdate, cli_gender, cli_email) values ('Andre Mendes', 'Alfornelos', str_to_date('2003.06.11','%Y.%m.%d'), 'M', 'mendesandre@sapo.pt');
insert into cliente (cli_name, cli_place, cli_bdate, cli_gender, cli_email) values ('Léa Silvestre', 'Seixal', str_to_date('1976.06.12','%Y.%m.%d'), 'F', 'silvestrelea@mac.com');
insert into cliente (cli_name, cli_place, cli_bdate, cli_gender, cli_email) values ('Mariana Barbosa', 'Amora', str_to_date('2004.06.17','%Y.%m.%d'), 'F', "barbmariana@sapo.pt");
insert into cliente (cli_name, cli_place, cli_bdate, cli_gender, cli_email) values ('Steve Vilas', 'São João do Estoril',str_to_date('2002.03.20','%Y.%m.%d'), 'M', 'villasteve@gmail.com');
insert into cliente (cli_name, cli_place, cli_bdate, cli_gender, cli_email) values ('Gabriela Borges', 'Amadora', str_to_date('2000.04.17','%Y.%m.%d'), 'F', 'borgesgabi@sapo.pt');

insert into modalidade (mod_name) values ('Soccer');
insert into modalidade (mod_name) values ('Futsal');
insert into modalidade (mod_name) values ('Padel');
insert into modalidade (mod_name) values ('Tennis');
insert into modalidade (mod_name) values ('Volleyball');
insert into modalidade (mod_name) values ('Golf');
insert into modalidade (mod_name) values ('Cycling');
insert into modalidade (mod_name) values ('Athletics');
insert into modalidade (mod_name) values ('Rugby');
insert into modalidade (mod_name) values ('Gym');
insert into modalidade (mod_name) values ('Basketball');
insert into modalidade (mod_name) values ('Handball');
insert into modalidade (mod_name) values ('Swimming');

insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Pavilhão do BES', 'Av. 24 de Julho 28, 1200-109 Lisboa', null, 2);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Campo de Futebol Bento Martins', 'R. Ana de Castro Osório 12A, 1500-431 Lisboa', null, 2);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Solinca - Colombo', 'C. Colombo Loja A 201 Avenida Lusíada, 1500-392 Lisboa', '21 012 9670', 10);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Ginásio Clube Português', 'Praça Ginásio Clube Português 1, 1250-111 Lisboa', '21 384 1580', 10);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Parque de Jogos 1º de Maio', 'Av. Rio de Janeiro, 1700-330 Lisboa', '21 845 3470', 10);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Piscina Municipal de Paio Pires', 'Av. 1 de Junho', '21 097 6060', 13);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Piscina Municipal Campo de Ourique', 'R. Correia Teles 103, 1350-104 Lisboa', '21 386 9541', 13);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Campo de Golfe Oitavos Dunes', 'Lote 64, 2750-040','21 486 0600', 6);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Golf Quinta da Marinha', 'R. Palmeiras n.º 247, 2750-005 Cascais', '21 486 0180', 6);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Estoril Golf Club', 'Av. República, 2765-273 Estoril', '21 468 0176', 6);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Pavilhão Municipal Cidade de Amora', 'R. António Macedo, 2845-047 Amora', null, 5);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Clube PlaySports - Voleibol', 'Largo José Joaquim Rodrigues 15, 2685-074 Sacavém', '913 259 683', 5);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Campo Mártires Basketball Court', 'Campo dos Mártires da Pátria 60006, 1150-228 Lisboa', null, 11);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Public Basketball Court Alcântara', 'PR3J+2C, 1350-352 Lisboa', null, 11);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Campo de basquetebol Laranjeiras', 'R. Olavo d Eça Leal 2, 1600-306 Lisboa', null, 11);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Boa Hora Futebol Clube', 'R. Aliança Operária 41, 1300-044 Lisboa', '21 362 8847', 12);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Athletics High Performance Center', 'Algés', null, 8); 
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Pista de Atletismo Professor Fernando Pereira', 'R. Nova 1, 2645-438 Alcabideche', null, 8);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Clube Ténis Monte Estoril', 'Av. Lago, 2765-423 Estoril', '917 347 388', 4); 
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Beloura Tennis Academy', 'Alameda da Beloura, Nº5, Quinta da Beloura, 2710-694 Sintra', '309 950 400', 4); 
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Campos Públicos de Ténis', 'Moita', null, 4);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Mr.Padel', 'Estrada Nacional N11, Complexo Desportivo da Quinta do Matão, 2860-403 Alhos Vedros', '964 138 898', 3);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Alverca Padel Club', 'Av. Infante Dom Pedro, 2615-357 Alverca do Ribatejo', '927 438 040', 3);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Campo Futebol Grupo Desportivo Vialonga', 'R. Passal, 2625-680 Vialonga', null, 1);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Myindoor Sacavém', 'R. Estado da Índia n2, 2685-002 Sacavém', '917 775 500', 1);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Campo ADCEO', 'R. da Q.ta de Santa Maria, 1800-325 Lisboa', '21 8510 203', 1);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Agronomia Rugby', 'Tapada da Ajuda 42, Lisboa', '961 047 984', 9);
insert into campos (camp_name, camp_place, camp_num, camp_mod_id) values ('Pista Municipal de Ciclismo de Loulé', 'R. Sebastião Cordeiro, 8100-638 Loulé', null, 7);

insert into MC (mc_mod_id, mc_camp_id) values (1,24);
insert into MC (mc_mod_id, mc_camp_id) values (1,25);
insert into MC (mc_mod_id, mc_camp_id) values (1,26);
insert into MC (mc_mod_id, mc_camp_id) values (2,1);
insert into MC (mc_mod_id, mc_camp_id) values (2,2);
insert into MC (mc_mod_id, mc_camp_id) values (3,22);
insert into MC (mc_mod_id, mc_camp_id) values (3,23);
insert into MC (mc_mod_id, mc_camp_id) values (4,19);
insert into MC (mc_mod_id, mc_camp_id) values (4,20);
insert into MC (mc_mod_id, mc_camp_id) values (4,21);
insert into MC (mc_mod_id, mc_camp_id) values (5,11);
insert into MC (mc_mod_id, mc_camp_id) values (5,12);
insert into MC (mc_mod_id, mc_camp_id) values (6,8);
insert into MC (mc_mod_id, mc_camp_id) values (6,9);
insert into MC (mc_mod_id, mc_camp_id) values (6,10);
insert into MC (mc_mod_id, mc_camp_id) values (7,28);
insert into MC (mc_mod_id, mc_camp_id) values (8,17);
insert into MC (mc_mod_id, mc_camp_id) values (8,18);
insert into MC (mc_mod_id, mc_camp_id) values (9,27);
insert into MC (mc_mod_id, mc_camp_id) values (10,3);
insert into MC (mc_mod_id, mc_camp_id) values (10,4);
insert into MC (mc_mod_id, mc_camp_id) values (10,5);
insert into MC (mc_mod_id, mc_camp_id) values (11,13);
insert into MC (mc_mod_id, mc_camp_id) values (11,14);
insert into MC (mc_mod_id, mc_camp_id) values (11,15);
insert into MC (mc_mod_id, mc_camp_id) values (12,16);
insert into MC (mc_mod_id, mc_camp_id) values (13,6);
insert into MC (mc_mod_id, mc_camp_id) values (13,7);

insert into horarios(hor_slot) values ('08h00 - 09h00');
insert into horarios(hor_slot) values ('09h00 - 10h00');
insert into horarios(hor_slot) values ('10h00 - 11h00');
insert into horarios(hor_slot) values ('11h00 - 12h00');
insert into horarios(hor_slot) values ('12h00 - 13h00');
insert into horarios(hor_slot) values ('13h00 - 14h00');
insert into horarios(hor_slot) values ('14h00 - 15h00');
insert into horarios(hor_slot) values ('15h00 - 16h00');
insert into horarios(hor_slot) values ('16h00 - 17h00');
insert into horarios(hor_slot) values ('17h00 - 18h00');
insert into horarios(hor_slot) values ('18h00 - 19h00');
insert into horarios(hor_slot) values ('19h00 - 20h00');
insert into horarios(hor_slot) values ('20h00 - 21h00');
insert into horarios(hor_slot) values ('21h00 - 22h00');
insert into horarios(hor_slot) values ('22h00 - 23h00');
insert into horarios(hor_slot) values ('23h00 - 00h00');

insert into MCH (mch_mc_id, mch_hor_id) values (1,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,14); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,15); 
insert into MCH (mch_mc_id, mch_hor_id) values (1,16); 
insert into MCH (mch_mc_id, mch_hor_id) values (2,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (2,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (2,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (2,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (2,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (2,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (2,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (2,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (2,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (2,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (2,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (2,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (2,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (2,14);
insert into MCH (mch_mc_id, mch_hor_id) values (2,15);
insert into MCH (mch_mc_id, mch_hor_id) values (2,16);
insert into MCH (mch_mc_id, mch_hor_id) values (3,1);
insert into MCH (mch_mc_id, mch_hor_id) values (3,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (3,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (3,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (3,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (3,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (3,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (3,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (3,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (3,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (3,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (3,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (3,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (3,14);
insert into MCH (mch_mc_id, mch_hor_id) values (3,15);
insert into MCH (mch_mc_id, mch_hor_id) values (3,16);
insert into MCH (mch_mc_id, mch_hor_id) values (4,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (4,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (4,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (4,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (4,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (4,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (4,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (4,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (4,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (4,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (4,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (4,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (4,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (4,14);
insert into MCH (mch_mc_id, mch_hor_id) values (4,15);
insert into MCH (mch_mc_id, mch_hor_id) values (4,16);
insert into MCH (mch_mc_id, mch_hor_id) values (5,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (5,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (5,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (5,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (5,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (5,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (5,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (5,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (5,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (5,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (5,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (5,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (5,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (5,14);
insert into MCH (mch_mc_id, mch_hor_id) values (5,15);
insert into MCH (mch_mc_id, mch_hor_id) values (5,16);
insert into MCH (mch_mc_id, mch_hor_id) values (6,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (6,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (6,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (6,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (6,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (6,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (6,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (6,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (6,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (6,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (6,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (6,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (6,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (6,14);
insert into MCH (mch_mc_id, mch_hor_id) values (6,15);
insert into MCH (mch_mc_id, mch_hor_id) values (6,16);
insert into MCH (mch_mc_id, mch_hor_id) values (7,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (7,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (7,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (7,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (7,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (7,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (7,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (7,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (7,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (7,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (7,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (7,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (7,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (7,14);
insert into MCH (mch_mc_id, mch_hor_id) values (7,15);
insert into MCH (mch_mc_id, mch_hor_id) values (7,16);
insert into MCH (mch_mc_id, mch_hor_id) values (8,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (8,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (8,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (8,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (8,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (8,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (8,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (8,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (8,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (8,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (8,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (8,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (8,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (8,14);
insert into MCH (mch_mc_id, mch_hor_id) values (8,15);
insert into MCH (mch_mc_id, mch_hor_id) values (8,16);
insert into MCH (mch_mc_id, mch_hor_id) values (9,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (9,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (9,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (9,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (9,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (9,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (9,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (9,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (9,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (9,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (9,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (9,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (9,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (9,14);
insert into MCH (mch_mc_id, mch_hor_id) values (9,15);
insert into MCH (mch_mc_id, mch_hor_id) values (9,16);
insert into MCH (mch_mc_id, mch_hor_id) values (10,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (10,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (10,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (10,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (10,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (10,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (10,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (10,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (10,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (10,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (10,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (10,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (10,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (10,14);
insert into MCH (mch_mc_id, mch_hor_id) values (10,15);
insert into MCH (mch_mc_id, mch_hor_id) values (10,16);
insert into MCH (mch_mc_id, mch_hor_id) values (11,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (11,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (11,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (11,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (11,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (11,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (11,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (11,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (11,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (11,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (11,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (11,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (11,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (11,14);
insert into MCH (mch_mc_id, mch_hor_id) values (11,15);
insert into MCH (mch_mc_id, mch_hor_id) values (11,16);
insert into MCH (mch_mc_id, mch_hor_id) values (12,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (12,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (12,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (12,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (12,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (12,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (12,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (12,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (12,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (12,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (12,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (12,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (12,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (12,14);
insert into MCH (mch_mc_id, mch_hor_id) values (12,15);
insert into MCH (mch_mc_id, mch_hor_id) values (12,16);
insert into MCH (mch_mc_id, mch_hor_id) values (13,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (13,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (13,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (13,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (13,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (13,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (13,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (13,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (13,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (13,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (13,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (13,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (13,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (13,14);
insert into MCH (mch_mc_id, mch_hor_id) values (13,15);
insert into MCH (mch_mc_id, mch_hor_id) values (13,16);
insert into MCH (mch_mc_id, mch_hor_id) values (14,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (14,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (14,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (14,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (14,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (14,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (14,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (14,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (14,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (14,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (14,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (14,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (14,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (14,14);
insert into MCH (mch_mc_id, mch_hor_id) values (14,15);
insert into MCH (mch_mc_id, mch_hor_id) values (14,16);
insert into MCH (mch_mc_id, mch_hor_id) values (15,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (15,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (15,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (15,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (15,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (15,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (15,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (15,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (15,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (15,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (15,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (15,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (15,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (15,14);
insert into MCH (mch_mc_id, mch_hor_id) values (15,15);
insert into MCH (mch_mc_id, mch_hor_id) values (15,16);
insert into MCH (mch_mc_id, mch_hor_id) values (16,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (16,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (16,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (16,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (16,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (16,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (16,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (16,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (16,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (16,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (16,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (16,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (16,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (16,14);
insert into MCH (mch_mc_id, mch_hor_id) values (16,15);
insert into MCH (mch_mc_id, mch_hor_id) values (16,16);
insert into MCH (mch_mc_id, mch_hor_id) values (17,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (17,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (17,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (17,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (17,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (17,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (17,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (17,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (17,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (17,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (17,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (17,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (17,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (17,14);
insert into MCH (mch_mc_id, mch_hor_id) values (17,15);
insert into MCH (mch_mc_id, mch_hor_id) values (17,16);
insert into MCH (mch_mc_id, mch_hor_id) values (18,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (18,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (18,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (18,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (18,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (18,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (18,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (18,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (18,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (18,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (18,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (18,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (18,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (18,14);
insert into MCH (mch_mc_id, mch_hor_id) values (18,15);
insert into MCH (mch_mc_id, mch_hor_id) values (18,16);
insert into MCH (mch_mc_id, mch_hor_id) values (19,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (19,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (19,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (19,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (19,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (19,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (19,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (19,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (19,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (19,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (19,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (19,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (19,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (19,14);
insert into MCH (mch_mc_id, mch_hor_id) values (19,15);
insert into MCH (mch_mc_id, mch_hor_id) values (19,16);
insert into MCH (mch_mc_id, mch_hor_id) values (20,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (20,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (20,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (20,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (20,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (20,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (20,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (20,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (20,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (20,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (20,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (20,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (20,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (20,14);
insert into MCH (mch_mc_id, mch_hor_id) values (20,15);
insert into MCH (mch_mc_id, mch_hor_id) values (20,16);
insert into MCH (mch_mc_id, mch_hor_id) values (21,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (21,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (21,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (21,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (21,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (21,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (21,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (21,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (21,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (21,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (21,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (21,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (21,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (21,14);
insert into MCH (mch_mc_id, mch_hor_id) values (21,15);
insert into MCH (mch_mc_id, mch_hor_id) values (21,16);
insert into MCH (mch_mc_id, mch_hor_id) values (22,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (22,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (22,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (22,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (22,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (22,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (22,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (22,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (22,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (22,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (22,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (22,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (22,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (22,14);
insert into MCH (mch_mc_id, mch_hor_id) values (22,15);
insert into MCH (mch_mc_id, mch_hor_id) values (22,16);
insert into MCH (mch_mc_id, mch_hor_id) values (23,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (23,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (23,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (23,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (23,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (23,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (23,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (23,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (23,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (23,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (23,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (23,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (23,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (23,14);
insert into MCH (mch_mc_id, mch_hor_id) values (23,15);
insert into MCH (mch_mc_id, mch_hor_id) values (23,16);
insert into MCH (mch_mc_id, mch_hor_id) values (24,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (24,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (24,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (24,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (24,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (24,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (24,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (24,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (24,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (24,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (24,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (24,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (24,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (24,14);
insert into MCH (mch_mc_id, mch_hor_id) values (24,15);
insert into MCH (mch_mc_id, mch_hor_id) values (24,16);
insert into MCH (mch_mc_id, mch_hor_id) values (25,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (25,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (25,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (25,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (25,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (25,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (25,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (25,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (25,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (25,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (25,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (25,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (25,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (25,14);
insert into MCH (mch_mc_id, mch_hor_id) values (25,15);
insert into MCH (mch_mc_id, mch_hor_id) values (25,16);
insert into MCH (mch_mc_id, mch_hor_id) values (26,1); 
insert into MCH (mch_mc_id, mch_hor_id) values (26,2); 
insert into MCH (mch_mc_id, mch_hor_id) values (26,3); 
insert into MCH (mch_mc_id, mch_hor_id) values (26,4); 
insert into MCH (mch_mc_id, mch_hor_id) values (26,5); 
insert into MCH (mch_mc_id, mch_hor_id) values (26,6); 
insert into MCH (mch_mc_id, mch_hor_id) values (26,7); 
insert into MCH (mch_mc_id, mch_hor_id) values (26,8); 
insert into MCH (mch_mc_id, mch_hor_id) values (26,9); 
insert into MCH (mch_mc_id, mch_hor_id) values (26,10); 
insert into MCH (mch_mc_id, mch_hor_id) values (26,11); 
insert into MCH (mch_mc_id, mch_hor_id) values (26,12); 
insert into MCH (mch_mc_id, mch_hor_id) values (26,13); 
insert into MCH (mch_mc_id, mch_hor_id) values (26,14);
insert into MCH (mch_mc_id, mch_hor_id) values (26,15);
insert into MCH (mch_mc_id, mch_hor_id) values (26,16);

insert into reserva(res_er_id, res_lob_id, res_mch_id, res_pdate) values (1,2,190, str_to_date('2023.12.15','%Y.%m.%d'));
insert into reserva(res_er_id, res_lob_id, res_mch_id, res_pdate)values (3,4,11, str_to_date('2023.12.17','%Y.%m.%d'));
insert into reserva(res_er_id, res_lob_id, res_mch_id, res_pdate) values (3,1,348, str_to_date('2023.12.20','%Y.%m.%d'));
insert into reserva(res_er_id, res_lob_id, res_mch_id, res_pdate) values (2,3,382, str_to_date('2023.12.22','%Y.%m.%d'));
insert into reserva(res_er_id, res_lob_id, res_mch_id, res_pdate) values (3,5,242, str_to_date('2023.12.25','%Y.%m.%d'));

insert into ER (er_name) values ('Canceled');
insert into ER (er_name) values ('Pending');
insert into ER (er_name) values ('Confirmed');

insert into lobby (lob_name, lob_cli_id) values ('Futsal 15/12 17h00 - 18h00', 1);
insert into lobby (lob_name, lob_cli_id) values ('Swimming 17/12 18h00 - 19h00', 8);
insert into lobby (lob_name, lob_cli_id) values ('Gym 20/12 08h00 - 09h00', 2);
insert into lobby (lob_name, lob_cli_id) values ('Padel 22/12 20h00 - 21h00', 6);
insert into lobby (lob_name, lob_cli_id) values ('Golf 25/12 09h00 - 10h00', 10);

insert into LU (lu_cli_id, lu_res_id) values (1,1);
insert into LU (lu_cli_id, lu_res_id) values (2,3);
insert into LU (lu_cli_id, lu_res_id) values (3,5);
insert into LU (lu_cli_id, lu_res_id) values (4,2);
insert into LU (lu_cli_id, lu_res_id) values (5,1);
insert into LU (lu_cli_id, lu_res_id) values (6,4);
insert into LU (lu_cli_id, lu_res_id) values (7,3);
insert into LU (lu_cli_id, lu_res_id) values (8,2);
insert into LU (lu_cli_id, lu_res_id) values (9,5);
insert into LU (lu_cli_id, lu_res_id) values (10,4);

insert into creditscore (cs_name) values ('Poor');
insert into creditscore (cs_name) values ('Fair'); 
insert into creditscore (cs_name) values ('Good'); 
insert into creditscore (cs_name) values ('Very Good');
insert into creditscore (cs_name) values ('Excellent');

insert into LUS (lus_cs_id, lus_lu_id) values (1,1);
insert into LUS (lus_cs_id, lus_lu_id) values (1,2);
insert into LUS (lus_cs_id, lus_lu_id) values (2,3);
insert into LUS (lus_cs_id, lus_lu_id) values (2,4);
insert into LUS (lus_cs_id, lus_lu_id) values (3,5);
insert into LUS (lus_cs_id, lus_lu_id) values (3,6);
insert into LUS (lus_cs_id, lus_lu_id) values (4,7);
insert into LUS (lus_cs_id, lus_lu_id) values (4,8);
insert into LUS (lus_cs_id, lus_lu_id) values (5,9);
insert into LUS (lus_cs_id, lus_lu_id) values (5,10);

commit;
